---
kind: pipeline
type: kubernetes
name: Upload

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: upload
    image: docker-private.averix.tech/prismarin/resourcepack-uploader:2.0.2
    environment:
      VAULT_TOKEN:
        from_secret: VAULT_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      BRANCH: main
---
kind: pipeline
type: kubernetes
name: Upload to dev

trigger:
  branch:
    - dev
  event:
    - push

steps:
  - name: upload
    image: docker-private.averix.tech/prismarin/resourcepack-uploader:2.0.2
    environment:
      VAULT_TOKEN:
        from_secret: VAULT_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      BRANCH: dev