---
kind: pipeline
type: docker
name: Upload

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: upload
    image: docker-private.averix.tech/prismarin/resourcepack-uploader
    environment:
      VAULT_TOKEN:
        from_secret: VAULT_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN